package uz.uzcard.genesis.hibernate.enums;

public enum EDSActionType {
    ACCEPT_STATUS_CHANGE_INITIATOR,
    ACCEPT_STATUS_CHANGE_OMTK,
    REJECT_STATUS_CHANGE_INITIATOR,
    REJECT_STATUS_CHANGE_OMTK,
    PART_ACCEPT_STATUS_CHANGE_INITIATOR,
    PART_ACCEPT_STATUS_CHANGE_OMTK,
    REMOVE_INITIATOR,
    REPLACE_INITIATOR,
    ADD_INITIATOR,
    TAKEN_AWAY_PRODUCT,
    PRODUCE_PRODUCT
}
