package uz.uzcard.genesis.hibernate.enums;

public interface Permissions {
    // Order
    String DEPARTMENT_ORDER_READ = "DEPARTMENT_ORDER_READ";
    String OMTK_ORDER_READ = "OMTK_ORDER_READ";
    String OZL_ORDER_READ = "OZL_ORDER_READ";

    String ORDER_CREATE = "ORDER_CREATE";
    String ORDER_ADD_FILES = "ORDER_ADD_FILES";
    String ORDER_SEND_TO_OMTK = "ORDER_SEND_TO_OMTK";
    String SEE_ALL_ORDER = "SEE_ALL_ORDER";

    // Order Item
    String ORDER_ITEM = "ORDER_ITEM";
    String DEPARTMENT_ORDER_ITEM_READ = "DEPARTMENT_ORDER_ITEM_READ";
    String OMTK_ORDER_ITEM_READ = "OMTK_ORDER_ITEM_READ";
    String OZL_ORDER_ITEM_READ = "OZL_ORDER_ITEM_READ";

    String ORDER_ITEM_CREATE = "ORDER_ITEM_CREATE";
    String ORDER_ITEM_DELETE = "ORDER_ITEM_DELETE";
    String ORDER_ITEM_UPDATE_COUNT = "ORDER_ITEM_UPDATE_COUNT";
    String ORDER_ITEM_OPPORTUNITY = "ORDER_ITEM_OPPORTUNITY";
    String ORDER_ITEM_ATTACH_AKT_FILES = "ORDER_ITEM_ATTACH_AKT_FILES";

    // Order Item Status
    String ORDER_ITEM_STATUS_REVIEW = "ORDER_ITEM_STATUS_REVIEW";
    String ORDER_ITEM_STATUS_ACCEPT = "ORDER_ITEM_STATUS_ACCEPT";
    String ORDER_ITEM_STATUS_SPECIFICATION = "ORDER_ITEM_STATUS_SPECIFICATION";
    String ORDER_ITEM_STATUS_TENDER = "ORDER_ITEM_STATUS_TENDER";
    String ORDER_ITEM_STATUS_REJECT = "ORDER_ITEM_STATUS_REJECT";
    String ORDER_ITEM_STATUS_PENDING_PURCHASE = "ORDER_ITEM_STATUS_PENDING_PURCHASE";
    String ORDER_ITEM_STATUS_REJECT_OZL = "ORDER_ITEM_STATUS_REJECT_OZL";
    String ORDER_ITEM_STATUS_CONTRACT_CONCLUTION = "ORDER_ITEM_STATUS_CONTRACT_CONCLUTION";
    String ORDER_ITEM_STATUS_CONTRACT_TERMINATE = "ORDER_ITEM_STATUS_CONTRACT_TERMINATE";

    // Contract
    String CONTRACT = "CONTRACT"; // /api/contract/list
    String CONTRACT_CREATE = "CONTRACT_CREATE"; // /api/contract/save
    String CONTRACT_CREATE_OZL = "CONTRACT_CREATE_OZL"; // /api/contract/save-ozl
    String CONTRACT_ACCEPT = "CONTRACT_ACCEPT"; // /api/contract/accept
    String CONTRACT_REJECT = "CONTRACT_REJECT"; // /api/contract/reject
    String CONTRACT_DELETE = "CONTRACT_DELETE"; // /api/contract/delete
    String CONTRACT_AGGREMENT_FILE_ADD = "CONTRACT_AGGREMENT_FILE_ADD"; // /api/contract/delete
    String CONTRACT_AGGREMENT_FILE_DELETED = "CONTRACT_AGGREMENT_FILE_DELETED"; // /api/contract/delete
    String SEE_ALL_CONTRACT = "SEE_ALL_CONTRACT";

    // Contract Item
    String CONTRACT_ITEM = "CONTRACT_ITEM"; // /api/contract/delete
    String CONTRACT_ITEM_ACCEPT = "CONTRACT_ITEM_ACCEPT"; // /api/contract/delete
    String CONTRACT_ITEM_REJECT = "CONTRACT_ITEM_REJECT";
    String CONTRACT_ITEM_CREATE = "CONTRACT_ITEM_CREATE";
    String CONTRACT_ITEM_CREATE_OZL = "CONTRACT_ITEM_CREATE_OZL";
    String CONTRACT_ITEM_PART_ACCEPT = "CONTRACT_ITEM_PART_ACCEPT";
    String CONTRACT_ITEM_DELETE = "CONTRACT_ITEM_DELETE";

    // Product
    String PRODUCT = "PRODUCT";
    String PRODUCT_CREATE = "PRODUCT_CREATE";
    String PRODUCT_DELETE = "PRODUCT_DELETE";

    // Product item
    String PRODUCT_ITEM = "PRODUCT_ITEM";
    String PRODUCT_ITEM_SPLIT = "PRODUCT_ITEM_SPLIT";

    // Realization
    String REALIZATION = "REALIZATION";

    // warehouse
    String WAREHOUSE = "WAREHOUSE";
    String WAREHOUSE_INCOME = "WAREHOUSE_INCOME";
    String SEE_ALL_WAREHOUSE = "SEE_ALL_WAREHOUSE";
    String SEE_ALL_WAREHOUSE_BY_TEAM = "SEE_ALL_WAREHOUSE_BY_TEAM";

    // Dashboard
    String DASHBOARD = "DASHBOARD";
}